// Generated by CoffeeScript 1.6.3
/*
This file is part of the Mooch package.

Copyright © 2013 Erin Millard

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.
*/


(function() {
  var Server, allow, allowStrings, deny, denyStrings, moment, options, os, pattern, server, _i, _j, _len, _len1;

  moment = require('moment');

  os = require('os');

  Server = require('./Server');

  allow = [];

  deny = [];

  if (process.env.MOOCH_ALLOW != null) {
    allowStrings = JSON.parse(process.env.MOOCH_ALLOW);
    for (_i = 0, _len = allowStrings.length; _i < _len; _i++) {
      pattern = allowStrings[_i];
      allow.push(new RegExp(pattern));
    }
  }

  if (process.env.MOOCH_DENY != null) {
    denyStrings = JSON.parse(process.env.MOOCH_DENY);
    for (_j = 0, _len1 = denyStrings.length; _j < _len1; _j++) {
      pattern = denyStrings[_j];
      deny.push(new RegExp(pattern));
    }
  }

  options = {
    consumerKey: process.env.MOOCH_CONSUMER_KEY,
    consumerSecret: process.env.MOOCH_CONSUMER_SECRET,
    twitterUri: process.env.MOOCH_TWITTER_URI,
    allow: allow,
    deny: deny
  };

  server = new Server(options);

  server.listen(process.env.PORT);

}).call(this);
