// Generated by CoffeeScript 1.6.3
(function() {
  var Server, util;

  util = require('util');

  module.exports = Server = (function() {
    function Server(options, request, http, output) {
      if (request == null) {
        request = require('request');
      }
      if (http == null) {
        http = require('http');
      }
      if (output == null) {
        output = process.stdout;
      }
      if (!options.consumerKey) {
        throw 'Consumer key is required.';
      }
      if (!options.consumerSecret) {
        throw 'Consumer secret is required.';
      }
      if (!options.port) {
        options.port = 8000;
      }
      if (!options.twitterUri) {
        options.twitterUri = 'https://api.twitter.com';
      }
      this._options = options;
      this._request = request;
      this._http = http;
      this._output = output;
    }

    Server.prototype.start = function(callback) {
      var _this = this;
      return this._obtainToken(function(error, token) {
        if (error) {
          _this._output.write('Unable to obtain bearer token, shutting down.');
          return callback(error);
        }
        _this._token = token;
        return _this._handle(callback);
      });
    };

    Server.prototype._obtainToken = function(callback) {
      var options,
        _this = this;
      options = {
        uri: this._options.twitterUri + '/oauth2/token',
        method: 'POST',
        headers: {
          authorization: util.format('Basic %s', this._generateRequestToken())
        },
        form: {
          grant_type: 'client_credentials'
        }
      };
      this._output.write('Obtaining bearer token... ');
      return this._request(options, function(error, response, body) {
        var responseVariables;
        if (error) {
          _this._output.write('unknown error.\n');
          return callback(error);
        } else {
          if (response.statusCode === 200) {
            responseVariables = JSON.parse(body);
            _this._output.write('done.\n');
            return callback(null, responseVariables.access_token);
          } else {
            _this._output.write(util.format('HTTP error (%s).\n', response.statusCode));
            return callback(response);
          }
        }
      });
    };

    Server.prototype._handle = function(callback) {
      var server,
        _this = this;
      server = this._http.createServer(function(request, response) {
        var requestBody;
        requestBody = '';
        request.on('readable', function() {
          return requestBody += request.read();
        });
        return request.on('end', function() {
          var options, property;
          options = {
            uri: _this._options.twitterUri + request.url,
            method: request.method,
            headers: request.headers,
            body: requestBody,
            followRedirect: false
          };
          for (property in options.headers) {
            if (property.toLowerCase() === 'host') {
              delete options.headers[property];
            }
          }
          options.headers.authorization = util.format('Bearer %s', _this._token);
          return _this._request(options).pipe(response);
        });
      });
      server.listen(this._options.port);
      this._output.write(util.format('Mooch listening on localhost:%d.\n', this._options.port));
      return callback(null);
    };

    Server.prototype._generateRequestToken = function() {
      var encodedConsumerKey, encodedConsumerSecret, encodedRequestPair;
      encodedConsumerKey = encodeURIComponent(this._options.consumerKey);
      encodedConsumerSecret = encodeURIComponent(this._options.consumerSecret);
      encodedRequestPair = util.format('%s:%s', encodedConsumerKey, encodedConsumerSecret);
      return new Buffer(encodedRequestPair).toString('base64');
    };

    return Server;

  })();

}).call(this);
